- name: Secrets tasks
  include_tasks:
    file: "secrets.yml"
    apply:
      tags: secrets
  tags: secrets

- name: Phd assess ged tasks
  include_tasks:
    file: "phd_assess_ged.yml"
    apply:
      tags: ged
  tags:
    - ged-build
    - ged-push
