- name: Locally build and tag phd-assess-meteor image
  tags:
    - ged-build
    - never
  shell: |
    set -e -x
    npm run build && docker build --tag {{ phd_assess_ged_servicename }} ..
  delegate_to: localhost
  register: output_docker_build
- debug: var=output_docker_build.stdout_lines
  tags:
    - ged-build
    - never

- name: Log into the Openshift docker repository and push the image
  tags:
    - ged-push
    - never
  shell: |
    set -e -x
    oc whoami -t | docker login {{ openshift_image_registry }} -u unused --password-stdin
    docker image tag {{ phd_assess_ged_servicename }} {{ phd_assess_ged_remote_image_tag }}
    docker push {{ phd_assess_ged_remote_image_tag }}
  register: output_push_image
  delegate_to: localhost
- debug: var=output_push_image.stdout_lines
  tags:
    - ged-push
    - never

- name: phd-assess-ged Deployment Config
  tags:
    - ged
  openshift:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: phd-assess-ged
      namespace: "{{openshift_namespace}}"
    spec:
      replicas: 1
      selector:
        deployment-config.name: phd-assess-ged
      strategy:
        activeDeadlineSeconds: 21600
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
        resources:
          limits:
            cpu: 1
            memory: 300M
      template:
        metadata:
          creationTimestamp: null
          labels:
            deployment-config.name: phd-assess-ged
        spec:
          containers:
            - env: "{{ deployment_envs }}"
              image: 'docker-registry.default.svc:5000/{{openshift_namespace}}/phd-assess-ged:latest'
              imagePullPolicy: Always
              name: phd-assess-ged
              resources:
                limits:
                  cpu: 1
                  memory: 300M
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: { }
          terminationGracePeriodSeconds: 30
      triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
          - phd-assess-ged
          from:
            kind: ImageStreamTag
            name: 'phd-assess-ged:latest'
            namespace: "{{openshift_namespace}}"
