- name: phd-assess secrets
  openshift:
    apiVersion: v1
    kind: Secret
    metadata:
      name: "{{ secret_name }}"
      namespace: "{{ openshift_namespace }}"
    type: Opaque
    data: >-
      {{ _data | from_yaml }}
  vars:
    _data: |
      "{{ encryption_key_name }}": "{{ lookup('file', '/keybase/team/epfl_phdassess/PHDASSESS_ENCRYPTION_KEY') | b64encode }}"

- name: phd-assess ged secrets
  openshift:
    apiVersion: v1
    kind: Secret
    metadata:
      name: "{{ ged_secret_name }}"
      namespace: "{{ openshift_namespace }}"
    type: Opaque
    data: >-
      {{ _data | from_yaml }}
  vars:
    _data: |
      "{{ alfresco_user_key_name }}": "{{ lookup('file', '/keybase/team/epfl_phdassess/ALFRESCO_USER') | b64encode }}"
      "{{ alfresco_password_key_name }}": "{{ lookup('file', '/keybase/team/epfl_phdassess/ALFRESCO_PASSWORD') | b64encode }}"
