
---
# vars file for epfl.phd-assess
app_name: "phd-assess-ged"
svc_name: "{{ app_name }}"
route_name: "{{ app_name }}"
phd_assess_ged_servicename: "phd-assess-ged"
openshift_image_registry: "os-docker-registry.epfl.ch"
openshift_local_image_registry: "docker-registry.default.svc:5000"
phd_assess_ged_image_tag: "{{openshift_image_registry}}/{{openshift_namespace}}/{{phd_assess_ged_servicename}}:latest"
secret_name: "phd-assess.secrets"
ged_secret_name: "phd-assess.ged.secrets"
encryption_key_name: "PHDASSESS_ENCRYPTION_KEY"
alfresco_user_key_name: "ALFRESCO_USER"
alfresco_password_key_name: "ALFRESCO_PASSWORD"
