
---
# vars file for epfl.phd-assess
app_name: "phd-assess-ged"
svc_name: "{{ app_name }}"
route_name: "{{ app_name }}"
phd_assess_ged_servicename: "phd-assess-ged"
openshift_image_registry: "os-docker-registry.epfl.ch"
openshift_local_image_registry: "docker-registry.default.svc:5000"
phd_assess_ged_remote_image_tag: "{{openshift_image_registry}}/{{openshift_namespace}}/{{phd_assess_ged_servicename}}:latest"
secret_name: "phd-assess.secrets"
ged_secret_name: "phd-assess.ged.secrets"
encryption_key_name: "PHDASSESS_ENCRYPTION_KEY"
alfresco_user_key_name: "ALFRESCO_USERNAME"
alfresco_password_key_name: "ALFRESCO_PASSWORD"
deployment_envs_common:
  - name: 'ZEEBE_ADDRESS'
    value: 'zeebe-gateway:26500'
  - name: 'ZEEBE_TASK_TYPE'
    value: 'phdGEDDeposit'
  - name: 'CONSOLE_LOG_JSON_NO_STACK_FOR_NON_ERROR'
    value: 'true'
  - name: 'CONSOLE_LOG_JSON_NO_FILE_NAME'
    value: 'true'
  - name: 'ALFRESCO_URL'
    value: "{{ alfresco_url }}"
  - name: "{{ encryption_key_name }}"
    valueFrom:
      secretKeyRef:
        name: "{{ secret_name }}"
        key: "{{ encryption_key_name }}"
  - name: "{{ alfresco_user_key_name }}"
    valueFrom:
      secretKeyRef:
        name: "{{ ged_secret_name }}"
        key: "{{ alfresco_user_key_name }}"
  - name: "{{ alfresco_password_key_name }}"
    valueFrom:
      secretKeyRef:
        name: "{{ ged_secret_name }}"
        key: "{{ alfresco_password_key_name }}"

deployment_envs: >-
  {{ deployment_envs_common + deployment_envs_specific if openshift_namespace == "phd-assess-test"
      else deployment_envs_common }}
